### ISSUE TITLE
feat: Option to not attach the log file to the email report

### ISSUE THREAD

**Issue by tysonsearls** [michaelmsonne/AzureDevOpsBackupTool#8]
# Feature Request

Option to not attach the log file to the email. 

an option in the command line to not attach log file. I have so many projects and branches that my email system will not process the email with a file size that big. The file size is 187MB

**Describe Alternatives**

**Related Code**

**Additional Context**

Sorry, we are unable to send email notification of your presence. Please try again! Error: System.Net.Mail.SmtpException: Exceeded storage allocation. The server response was: 5.3.4 Error: message file too big
   at System.Net.Mail.DataStopCommand.CheckResponse(SmtpStatusCode statusCode, String serverResponse)
   at System.Net.Mail.DataStopCommand.Send(SmtpConnection conn)
   at System.Net.ClosableStream.Close()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at AzureDevOpsBackup.Class.ReportSender.SendEmail(String serverAddress, String serverPort, String emailFrom, String emailTo, String emailStatusMessage, List`1 repoCountElements, List`1 repoItemsCountElements, Int32 repoCount, Int32 repoItemsCount, Int32 totalFilesIsBackupUnZipped, Int32 totalBlobFilesIsBackup, Int32 totalTreeFilesIsBackup, String outDir, String elapsedTime, Int32 errors, Int32 totalFilesIsDeletedAfterUnZipped, Int32 totalBackupsIsDeleted, String daysToKeep, String repoCountStatusText, String repoItemsCountStatusText, String totalFilesIsBackupUnZippedStatusText, String totalBlobFilesIsBackupStatusText, String totalTreeFilesIsBackupStatusText, String totalFilesIsDeletedAfterUnZippedStatusText, String letOverZipFilesStatusText, String letOverJsonFilesStatusText, String totalBackupsIsDeletedStatusText, Boolean useSimpleMailReportLayout, String isOutputFolderContainFilesStatusText, String isDaysToKeepNotDefaultStatusText, String startTime, String endTime, Boolean deletedFilesAfterUnzip, Boolean checkForLeftoverFilesAfterCleanup)
**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by michaelmsonne** [comment]
Hi @tysonsearls ,

Good idear - will note that that, and work on that :)

**Comment by michaelmsonne** [comment]
Have added this option to the upcomming v. 1.1.0.0 i'm in the makeing of with a new argument '--noattatchlog' :)

I close this issues with this note, and my plan is to release it soon.

**Comment by michaelmsonne** [comment]
And with that log size, it´s good here is a cleanup feature I see! :D

**Comment by michaelmsonne** [comment]
@tysonsearls released here with this add :)

https://github.com/michaelmsonne/AzureDevOpsBackupTool/releases/tag/1.1.0.0
